stages:
  - test-first       # Fedora Linux with gcc and {OpenSSL,GnuTLS}

variables:
  BUILD_IMAGES_PROJECT: openconnect/build-images
  CENTOS7_BUILD: openconnect-cli-centos7
  CENTOS8_BUILD: openconnect-cli-centos8
  CENTOS9_BUILD: openconnect-cli-centos9
  FEDORA_BUILD: openconnect-cli-fedora39
  MINGW32_BUILD: openconnect-cli-mingw32
  MINGW64_BUILD: openconnect-cli-mingw64
  UBUNTU_BUILD: openconnect-cli-ubuntu
  ANDROID_BUILD: openconnect-cli-android-r21e
  ANDROID_TOOLCHAINDIR: /opt/android-sdk-linux_x86/toolchains

image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD

Fedora/OpenSSL:
  stage: test-first
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD
  script:
# Re-enable DSA since we test it
  - update-crypto-policies --set LEGACY
  - ./autogen.sh
  - ./configure --without-gnutls --with-openssl --without-openssl-version-check --disable-dsa-tests --enable-ppp-tests CFLAGS=-g
  - make tmp-distdir
  - nslookup localhost
  - mkdir build
  - cd build
  - TMPDISTDIR=../openconnect-$(git describe --tags | sed s/^v//)
  - ${TMPDISTDIR}/configure --without-gnutls --with-openssl --without-openssl-version-check --disable-dsa-tests --enable-ppp-tests CFLAGS=-g
  - make -j4
# For reasons that are unclear, but probably also unimportant, IPv6 is disabled by default on this CI
# image (verified in https://gitlab.com/openconnect/openconnect/-/jobs/1135199323#L335), and this will
# cause PPP tests using IPv6 to fail. So we must explicitly enable IPv6:
  - sysctl net.ipv6.conf.all.disable_ipv6=0
# we don't want pppd to invoke any actual connection scripts
  - mv /etc/ppp /etc/ppp.DISABLED
# auth-swtpm: XFAIL until we understand the TPM error
# obsolete-server-crypto: obsolete crypto has been removed from LEGACY crypto policies
# ppp-over-tls-sync: https://gitlab.com/openconnect/openconnect/-/issues/287#note_641198529)
  - make VERBOSE=1 XFAIL_TESTS="auth-swtpm obsolete-server-crypto ppp-over-tls-sync" -j4 check
  tags:
  - saas-linux-small-amd64
  except:
  - tags
  - schedules
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - build/tests/*.log

